document.getElementById("dropDownTitle_6_0").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_1").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_2").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_3").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_4").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_5").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_6").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_7").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_8").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_9").textContent="Schedule Date"
document.getElementById("dropDownTitle_6_10").textContent="Schedule Date"

document.getElementById("dropDownTitle_7_0").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_1").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_2").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_3").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_4").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_5").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_6").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_7").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_8").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_9").textContent="Schedule Date"
document.getElementById("dropDownTitle_7_10").textContent="Schedule Date"

